name: Build and commit 3mfs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '*.scad'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Render in OpenSCAD
        run: |
          set -euxo pipefail
          docker run --rm -v $PWD:/work -w /work openscad/openscad:dev \
            bash -c 'apt-get install -y make && make clean all'
      - name: Commit changes
        run: |
          set -euxo pipefail
          git config --global user.name "GitHub Actions"
          git config --global user.email "githubactions@github.com"
          git add -f stls/
          git commit -m "Render 3mfs"
          git push origin HEAD:${$GITHUB_REF}